apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: jvm-cfl-example
  namespace: app
spec:
  schedule: '@every 1m'
  type: JVMChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  jvm_chaos:
    action: cfl
    target: jvm
    mode: one
    selector:
      labelSelectors:
        app: springboot-jvmchaos-demo
    duration: 30s
